version: "3.7"

services:
  pgsql:
    build: docker/pgsql
    restart: always
    container_name: code2_pgsql
#    volumes:
#      - "./docker/volumes/pgsql:/var/lib/postgresql/data"
#      - "./docker/pgsql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: 'code'
      POSTGRES_USER: 'code'
      POSTGRES_PASSWORD: 'code'
    ports:
      - "5432"
    networks:
      - backend


#    image: "library/postgres:13-alpine"
#    volumes:
#      - "./docker/volumes/pgsql:/var/lib/postgresql/data"
#      - "./docker/pgsql:/docker-entrypoint-initdb.d"
#    environment:
#      POSTGRES_DB: 'code'
#      POSTGRES_USER: 'code'
#      POSTGRES_PASSWORD: 'code'
##    ports: ["5430:5432"]
#    ports: ["127.0.0.1:5430:5432"]
#    networks:
#      - backend

  app:
#    image: app
    container_name: code2_php
    build: ./docker/app
    volumes:
      - ./:/var/www/app
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - pgsql
    networks:
      - backend

  nginx:
    container_name: code2_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/app
      - ./var/log/nginx:/var/log/nginx:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/server.conf:/etc/nginx/server.conf:ro
    ports: ["8088:80"]
    depends_on:
      - app
    networks:
      - backend

networks:
  backend: